config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :create, :show]

  resources :events, only: [:show, :index]

  post '/events/:id', to: 'events#register'

  get '/create_event', to: 'events#new'

  post '/create_event', to: 'events#create'

  get '/signup', to: 'users#new'
  
  post '/signup', to: 'users#create'
  
  get '/login', to: 'sessions#new'
  
  post '/login', to: 'sessions#create'
  
  delete '/logout', to: 'sessions#destroy'
  
  root 'static_pages#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
    belongs_to :creator, class_name: "User", foreign_key: "user_id"
    has_many :invites
    has_many :attendees, through: :invites
    
    scope :upcoming, -> { where("date > ?", Time.zone.now) }
    scope :past, -> { where("date <= ?", Time.zone.now) }
    
    validates :name, presence: true
    validates :description, presence: true
    validates :date, presence: true
    validates :time, presence: true

    def formated_datetime
        date.strftime("%B %e") + time.strftime(" @ %l:%M %P") unless date.nil?
    end
end

app/models/invite.rb
class Invite < ApplicationRecord
    belongs_to :attended_event, class_name: "Event", foreign_key: "event_id"
    belongs_to :attendee, class_name: "User", foreign_key: "user_id"
    
    attr_accessor :accepted
end

app/models/user.rb
class User < ApplicationRecord
    validates :name, presence: true
    validates :email, presence: true

    has_many :invites
    has_many :events
    has_many :attended_events , :through => :invites
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :logged_in?, only: [:new, :create, :show]

  def new
    @event = Event.new
  end

  def create
    @event = current_user.events.build(event_params)
    if @event.save
      flash[:success] = "Event successfully created"
      register_user_for_event(current_user, @event)
      redirect_to current_user
    else
      render :new
    end
  end

  def show
    @event = Event.find(params[:id])
    @user = current_user
  end

  def index
    @events = Event.all
    @upcoming_events = Event.upcoming
    @past_events = Event.past
  end

  def register
    @event = Event.find(params[:id])
    if register_user_for_event(current_user, @event)
      flash.now[:success] = "Successfully registered for #{@event.name}!"
      redirect_to @event
    else
      flash[:danger] = "Unsuccessful registration"
      redirect_to @event
    end
  end

  private
  
  def register_user_for_event(user, event)
    event.attendees << user
  end
  
  def event_params
    params.require(:event).permit(:name, :description, :date, :time)
  end
  
  # Filters

  def logged_in?
    if current_user.nil?
      flash[:warning] = 'You need to be logged in to do that!'
      redirect_to login_path
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
    end
    
    def create
        @user = User.find_by(email: params[:session][:email])
        if @user
            log_in @user
            flash[:success] = "Log in successful!"
            redirect_to root_url
        else
            flash.now[:danger] = "Email not found!"
            render :new
        end
    end
    
    def destroy
        log_out
        flash[:warning] = "Log out successful!"
        redirect_to root_url
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
    def home
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    
    def new
        @user = User.new
    end
    
    def create
        @user = User.new(user_params)
        if @user.save
            flash[:success] = "Welcome to Brite Event!"
            log_in @user
            redirect_to @user
        else
            render :new
        end
    end
    
    def show
        @user = User.find(params[:id])
        @past_events = @user.events.where("date < ?", Time.now)
        @upcoming_events = @user.events.where("date > ?", Time.now)
    end
    
    private
    
    def user_params
        params.require(:user).permit(:name, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
  def registered?(user)
    attendees.include?(user)
  end
end

app/helpers/invites_helper.rb
module InvitesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    
    def log_in(user)
        session[:user_id] = user.id
    end
    
    def logged_in?
        !current_user.nil?
    end

    def current_user?(user)
        @current_user == user
    end

    def current_user
        @current_user ||= User.find_by(id: session[:user_id])
    end
    
    def log_out
        session.delete(:user_id)
        @current_user = nil
    end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/index.html.erb
<div class='row center-align'>
  <div class='col l3 s12'>
      <%= link_to 'Create Event!', create_event_path, class: 'btn btn-large waves-effect waves-light', id: 'create-event' %>
  </div>

  <div class='col l6 s12'>
    <h4>Upcoming Events</h4>
    <% if @events.upcoming.any? %>
        <% @events.upcoming.each do |event| %>
        <div class="card is-primary">
            <div class="card-content white-text">
              <span class="card-title left-align"><%= link_to event.name.capitalize, event_path(event.id) %></span>
              <p class="black-text"><%= event.description %></p>
            </div>
            <div class="card-action">
              <span>hosted by <%= link_to event.creator.name.capitalize, event.creator, class: "red-text" %></span>
              <span class="date grey-text"><%= event.formated_datetime %></span></span>
            </div>
        </div>
        <% end %>
    <% else %>
        <section><p>No upcoming events to show!</p></section>
    <% end %>
    
    <h4>Past Events</h4>
    <% if @events.past.any? %>
        <% @events.past.each do |event| %>
        <div class="card is-primary">
            <div class="card-content white-text">
              <span class="card-title left-align"><%= link_to event.name.capitalize, event_path(event.id) %></span>
              <p class="black-text"><%= event.description %></p>
            </div>
            <div class="card-action">
              <span>hosted by <%= link_to event.creator.name.capitalize, event.creator, class: "red-text" %></span>
              <span class="date grey-text"><%= event.formated_datetime %></span></span>
            </div>
        </div>
        <% end %>
    <% else %>
        <section><p>No past events to show!</p></section>
    <% end %>
  </div>
</div>

app/views/events/new.html.erb
<div class="row">
  <div class="col l12 s12">
    <h1>Create an event!</h1>
  </div>
</div>
<div class='row'>
  <%= form_for :event, :html => {class: "col l12 s12"} do |f| %>
      <% if @event.errors.any? %>
          <div id="error_explanation" class='col l6 offset-l3 s12 red'>
            <h5><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h5>

            <ul>
              <% @event.errors.full_messages.each do |msg| %>
                  <li class="white"><%= msg %></li>
              <% end %>
            </ul>
          </div>
      <% end %>
      <div class="row">
        <div class="input-field col l6 offset-l3 s12">
          <%= f.label :name %>
          <%= f.text_field :name, class: 'validate' %>
        </div>
      </div>

      <div class="row">
        <div class="input-field col l6 offset-l3 s12">
          <%= f.label :description %>
          <%= f.text_field :description, class: 'validate' %>
        </div>
      </div>

      <div class="row">
        <div class="input-field col l3 offset-l3 s12">
          <%= f.label :date %>
          <%= f.text_field :date, class: 'datepicker' %>
        </div>

        <div class="input-field col l3 s12">
          <%= f.label :time %>
          <%= f.text_field :time, class: 'timepicker' %>
        </div>
      </div>

      <%= f.submit 'Create!', class: 'waves-effect waves-light btn-large' %>

  <% end %>
</div>

app/views/events/show.html.erb
<div class="row">
  <div class="col l3 s12">
    <h3><%= @event.name %></h3>
    <h5><span class="date grey-text"><%= @event.formated_datetime %></span></h5>
    <h6>Host: <%= link_to @event.creator.name, @event.creator %></h6>
    <h6><%= pluralize(@event.attendees.count, "guest") %></h6>
    <% unless @event.attendees.find_by(id: @user.id) %>
      <%= link_to "Register!", event_path(:id => @event.id), class: "waves-effect waves-light btn-large", method: :post %>
    <% end %>
    <ul class="collection with-header">
      <li class="collection-header"><h5>Guest List</h5></li>
    <% @event.attendees.each do |attendee| %>
        <li class="collection-item"><%= link_to attendee.name, attendee %></li>
    <% end %>
    </ul>
  </div>
  <div class='col l6 s12'>
    <h6 class='left-align'><%= @event.description %></h6>
  </div>
</div>

app/views/layouts/_header.html.erb
<nav>
    <div class="nav-wrapper">
        <%= link_to 'Brite Event', root_url, class: "brand-logo"%>
        <a href="#" data-activates="mobile" class="button-collapse"><i class="material-icons">menu</i></a>
        <ul id="nav-mobile" class="right hide-on-med-and-down">
            <% if logged_in? %>
                <li><%= link_to "#{@current_user.name.capitalize}", @current_user %></li>
                <li><%= link_to "Browse Events", events_path %></li>
                <li><%= link_to 'Log out', logout_path, method: :delete %></li>
            <% else %>
                <li><%= link_to 'Log in', login_path %></li>
                <li><%= link_to 'Sign up', signup_path %></li>
            <% end %>
        </ul>
        <ul class="side-nav" id="mobile">
            <% if logged_in? %>
                <li><%= link_to "#{@current_user.name.capitalize}", @current_user %></li>
                <li><%= link_to "Browse Events", events_path %></li>
                <li><%= link_to 'Log out', logout_path, method: :delete %></li>
            <% else %>
                <li><%= link_to 'Log in', login_path %></li>
                <li><%= link_to 'Sign up', signup_path %></li>
            <% end %>
        </ul>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BriteEvent</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'https://fonts.googleapis.com/icon?family=Material+Icons' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container center-align">
      <% flash.each do |msg_type, msg| %>
      <div class="row">
        <div class="col l4 offset-l4 s12">
          <%= content_tag(:div, msg, class: "card-panel #{msg_type}") %>
        </div>
      </div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/static_pages/home.html.erb
<div class="row">
    <div class="col l12 s12">
        <h1>Welcome to Brite Event!</h1>
    </div>
</div>
<div class="row">
    <div class="col l12 s12">
      <% if logged_in? %>
        <%= link_to 'Create event!' , create_event_path, class: "waves-effect waves-light btn-large"%><br>
          <p>Or <%= link_to "Browse Events", events_path %></p>
      <% else %>
        <%= link_to 'Sign Up!', signup_path, class: "waves-effect waves-light btn-large s12" %>
      <% end %>
    </div>
</div>

app/views/users/new.html.erb
<div class="row">
    <div class="col l6 offset-l3 s12">
        <h1>Sign Up!</h1>
    </div>
</div>
<%= form_for @user, :html => {class: "row"} do |f| %>
    <% if @user.errors.any? %>
        <div id="error_explanation" class='col l6 offset-l3 s12 red'>
            <h5><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h5>

            <ul>
                <% @user.errors.full_messages.each do |msg| %>
                    <li class="white"><%= msg %></li>
                <% end %>
            </ul>
        </div>
    <% end %>
    <div class="row">
        <div class="input-field col l6 offset-l3 s12">
        <%= f.label :name %>
        <%= f.text_field :name, class: 'validate', size: 35 %>
        </div>
    </div>
    <div class="row">
        <div class="input-field col l6 offset-l3 s12">
            <%= f.label :email %>
            <%= f.text_field :email, class: 'validate', size: 35 %>
        </div>
    </div>
    <div class="row">
      <%= f.submit 'Sign up!', class: "waves-effect waves-light btn-large" %>
    </div>
<% end %>

app/views/users/show.html.erb
<div class='row'>
    <div class='col l3 s12 center-on-small-only'>
        <h5 class='left-on'><%= "#{@user.name.capitalize}" %></h5>
            <% if @user.attended_events.upcoming.any? %>
              <ul class="collection with-header">
                <li class="collection-header"><h5>Attending events</h5></li>
              <% @user.attended_events.upcoming.each do |event| %>
                <li class="collection-item"><%= link_to event.name, event %></li>
              <% end %>
            <% end %>
          </ul>
        <%= link_to 'Create Event!', create_event_path, class: 'btn btn-large waves-effect waves-light', id: 'create-event' %>
    </div>
    <div class='col l6 s12'>
        <% if @user.events.any? %>
            <h4>Upcoming Events</h4>
            <% if @upcoming_events.any? %>
                <% @upcoming_events.each do |event| %>
                <div class="card is-primary">
                    <div class="card-content white-text">
                      <span class="card-title left-align"><%= link_to event.name.capitalize, event_path(event.id) %></span>
                      <p class="black-text"><%= event.description %></p>
                    </div>
                    <div class="card-action">
                      <span>hosted by <%= link_to event.creator.name.capitalize, event.creator, class: "red-text" %></span>
                      <span class="date grey-text"><%= event.formated_datetime %></span></span>
                    </div>
                </div>
                <% end %>
            <% else %>
                <section><p>No upcoming events for this user!</p></section>
            <% end %>
            <h4>Past Events</h4>
            <% if @past_events.any? %>
                <% @past_events.each do |event| %>
                <div class="card is-primary">
                    <div class="card-content white-text">
                      <span class="card-title left-align"><%= link_to event.name.capitalize, event_path(event.id) %></span>
                      <p class="black-text"><%= event.description %></p>
                    </div>
                    <div class="card-action">
                      <span>hosted by <%= link_to event.creator.name.capitalize, event.creator, class: "red-text" %></span>
                      <span class="date grey-text"><%= event.formated_datetime %></span></span>
                    </div>
                </div>
                <% end %>
            <% else %>
                <section class='left-align'><p>No past events for this user!</p></section>
            <% end %>
        <% else %>
            <section class='left-align'><p>No events for this user!</p></section>
        <% end %>
    </div>
</div>